// Project templates for README generation in React Native
// Each template is an object with name, description, and an array of elements
// Elements use the same structure as the converted ReadmeElement models

import {
  HeadingElement,
  BadgeElement,
  ParagraphElement,
  ListElement,
  CodeBlockElement,
  GitHubStatsElement,
  SocialProfile,
  SocialsElement,
  TOCElement,
  TableElement,
  CollapsibleElement,
  ContributorsElement,
  DynamicWidgetElement,
  DividerElement,
  BlockquoteElement,
  ImageElement,
  LinkButtonElement,
  IconElement,
} from '../models/ReadmeElement';

export const templates = [
  {
    name: 'Minimal',
    description: 'Basic structure with Project Name, Description, and License.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME]', level: 1 }),
      new BadgeElement({ label: 'License', imageUrl: 'https://img.shields.io/badge/license-MIT-blue.svg', targetUrl: '' }),
      new ParagraphElement({ text: "A brief description of what this project does and who it's for." }),
      new HeadingElement({ text: 'License', level: 2 }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
  {
    name: 'Library / Package',
    description: 'Includes Installation, Usage, and Example sections.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME]', level: 1 }),
      new BadgeElement({ label: 'Version', imageUrl: 'https://img.shields.io/pub/v/[PROJECT_NAME]', targetUrl: 'https://pub.dev/packages/[PROJECT_NAME]' }),
      new BadgeElement({ label: 'License', imageUrl: 'https://img.shields.io/badge/license-MIT-blue.svg', targetUrl: '' }),
      new BadgeElement({ label: 'Build Status', imageUrl: 'https://img.shields.io/github/actions/workflow/status/[GITHUB_USERNAME]/[PROJECT_NAME]/main.yml', targetUrl: '' }),
      new ParagraphElement({ text: 'A powerful library for...' }),
      new HeadingElement({ text: 'Features', level: 2 }),
      new ListElement({ items: ['Feature 1', 'Feature 2', 'Feature 3'] }),
      new HeadingElement({ text: 'Installation', level: 2 }),
      new CodeBlockElement({ code: 'flutter pub add [PROJECT_NAME]', language: 'bash' }),
      new HeadingElement({ text: 'Usage', level: 2 }),
      new CodeBlockElement({ code: "import '[PROJECT_NAME]/[PROJECT_NAME].dart';\n\nvoid main() {\n  // Use the library\n}", language: 'dart' }),
      new HeadingElement({ text: 'License', level: 2 }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
  {
    name: 'Open Source Pro',
    description: 'A polished README with badges, quickstart, roadmap, and contributors.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME]', level: 1 }),
      new ParagraphElement({ text: 'Build beautiful documentation fast with MD Studio.' }),
      new BadgeElement({ label: 'Stars', imageUrl: 'https://img.shields.io/github/stars/[GITHUB_USERNAME]/[PROJECT_NAME]?style=for-the-badge', targetUrl: 'https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME]' }),
      new BadgeElement({ label: 'Issues', imageUrl: 'https://img.shields.io/github/issues/[GITHUB_USERNAME]/[PROJECT_NAME]?style=for-the-badge', targetUrl: 'https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME]/issues' }),
      new BadgeElement({ label: 'License', imageUrl: 'https://img.shields.io/github/license/[GITHUB_USERNAME]/[PROJECT_NAME]?style=for-the-badge', targetUrl: 'https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME]/blob/main/LICENSE' }),
      new BadgeElement({ label: 'Build', imageUrl: 'https://img.shields.io/github/actions/workflow/status/[GITHUB_USERNAME]/[PROJECT_NAME]/ci.yml?style=for-the-badge', targetUrl: 'https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME]/actions' }),
      new DividerElement({}),
      new TOCElement({ title: 'Contents' }),
      new HeadingElement({ text: 'Features', level: 2 }),
      new ListElement({ items: ['Drag & drop editor', 'Live preview + export', 'Templates + snippets library', 'GitHub publish workflow'] }),
      new HeadingElement({ text: 'Quickstart', level: 2 }),
      new CodeBlockElement({ language: 'bash', code: 'npm install\nnpm run web' }),
      new HeadingElement({ text: 'Usage', level: 2 }),
      new CodeBlockElement({ language: 'markdown', code: '## Example\n\nAdd elements from the left panel, then export.' }),
      new HeadingElement({ text: 'Roadmap', level: 2 }),
      {
        type: 'taskList',
        items: [
          { text: 'Add more templates', checked: true },
          { text: 'GitHub OAuth connect', checked: false },
          { text: 'Phone OTP sign-in', checked: false },
          { text: 'Team workspaces', checked: false },
        ],
      },
      new HeadingElement({ text: 'Contributing', level: 2 }),
      new CollapsibleElement({ summary: 'How to contribute', content: '1) Fork\n2) Create a branch\n3) Submit a PR\n\nThanks for helping!' }),
      new HeadingElement({ text: 'Community', level: 2 }),
      new SocialsElement({
        style: 'for-the-badge',
        profiles: [
          new SocialProfile({ platform: 'GitHub', username: '[GITHUB_USERNAME]' }),
          new SocialProfile({ platform: 'X (Twitter)', username: '[GITHUB_USERNAME]' }),
          new SocialProfile({ platform: 'LinkedIn', username: '[GITHUB_USERNAME]' }),
        ],
      }),
      new HeadingElement({ text: 'Contributors', level: 2 }),
      new ContributorsElement({ repoName: '[GITHUB_USERNAME]/[PROJECT_NAME]', style: 'grid' }),
      new HeadingElement({ text: 'Stats', level: 2 }),
      new GitHubStatsElement({ repoName: '[GITHUB_USERNAME]/[PROJECT_NAME]' }),
      new HeadingElement({ text: 'License', level: 2 }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
  {
    name: 'Mobile App',
    description: 'Great for apps: screenshots, features, store links, and tech stack.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME]', level: 1 }),
      new ParagraphElement({ text: 'A modern mobile app experience built for speed and clarity.' }),
      new ImageElement({ url: 'https://raw.githubusercontent.com/[GITHUB_USERNAME]/[PROJECT_NAME]/main/assets/cover.png', altText: 'App cover', width: 900 }),
      new ParagraphElement({ text: 'Try it: ' }),
      new LinkButtonElement({ text: 'Download (Play Store)', url: 'https://play.google.com/store/apps/details?id=com.example.app' }),
      new LinkButtonElement({ text: 'Download (App Store)', url: 'https://apps.apple.com/app/id0000000000' }),
      new DividerElement({}),
      new HeadingElement({ text: 'Highlights', level: 2 }),
      new ListElement({ items: ['Beautiful UI', 'Offline-first', 'Fast sync', 'Dark mode + themes'] }),
      new HeadingElement({ text: 'Tech Stack', level: 2 }),
      new IconElement({ name: 'React Native', url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', size: 28 }),
      new IconElement({ name: 'TypeScript', url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', size: 28 }),
      new IconElement({ name: 'Firebase', url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg', size: 28 }),
      new HeadingElement({ text: 'Install', level: 2 }),
      new CodeBlockElement({ language: 'bash', code: 'npm install\nnpm run android\n# or\nnpm run ios' }),
      new HeadingElement({ text: 'Configuration', level: 2 }),
      new TableElement({ headers: ['Key', 'Description'], rows: [['FIREBASE_API_KEY', 'Firebase web config'], ['GITHUB_TOKEN', 'Optional token for publishing']] }),
      new HeadingElement({ text: 'License', level: 2 }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
  {
    name: 'API / Backend Service',
    description: 'Perfect for services: endpoints, env vars, and deployment notes.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME] API', level: 1 }),
      new BadgeElement({ label: 'Status', imageUrl: 'https://img.shields.io/badge/status-active-success?style=for-the-badge', targetUrl: '' }),
      new BadgeElement({ label: 'License', imageUrl: 'https://img.shields.io/github/license/[GITHUB_USERNAME]/[PROJECT_NAME]?style=for-the-badge', targetUrl: '' }),
      new ParagraphElement({ text: 'A production-ready backend with a clean architecture and clear docs.' }),
      new HeadingElement({ text: 'Endpoints', level: 2 }),
      new TableElement({
        headers: ['Method', 'Path', 'Description'],
        rows: [
          ['GET', '/health', 'Health check'],
          ['POST', '/auth/login', 'Login'],
          ['GET', '/v1/items', 'List items'],
        ],
      }),
      new HeadingElement({ text: 'Environment', level: 2 }),
      new TableElement({
        headers: ['Variable', 'Required', 'Notes'],
        rows: [
          ['PORT', 'No', 'Default: 3000'],
          ['DATABASE_URL', 'Yes', 'Postgres connection string'],
          ['JWT_SECRET', 'Yes', 'Keep it safe'],
        ],
      }),
      new HeadingElement({ text: 'Run locally', level: 2 }),
      new CodeBlockElement({ language: 'bash', code: 'npm install\nnpm run dev' }),
      new HeadingElement({ text: 'Deploy', level: 2 }),
      new BlockquoteElement({ text: 'Tip: Use a reverse proxy + HTTPS in production.' }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
  {
    name: 'Portfolio / Profile',
    description: 'A profile-style README: about, projects, and contact links.',
    elements: [
      new HeadingElement({ text: "Hi, I'm [GITHUB_USERNAME]", level: 1 }),
      new ParagraphElement({ text: 'Welcome to my portfolio. I build products with strong UX and clean code.' }),
      new HeadingElement({ text: 'About', level: 2 }),
      new ListElement({ items: ['Focus: UI engineering + tools', 'Building: [PROJECT_NAME]', 'Contact: hello@example.com'] }),
      new HeadingElement({ text: 'Featured Projects', level: 2 }),
      new TableElement({
        headers: ['Project', 'What it does', 'Link'],
        rows: [
          ['[PROJECT_NAME]', 'Markdown creator + export', 'https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME]'],
          ['Starter Kit', 'Reusable app template', 'https://github.com/[GITHUB_USERNAME]/starter-kit'],
        ],
      }),
      new HeadingElement({ text: "Let's connect", level: 2 }),
      new SocialsElement({
        style: 'for-the-badge',
        profiles: [
          new SocialProfile({ platform: 'GitHub', username: '[GITHUB_USERNAME]' }),
          new SocialProfile({ platform: 'LinkedIn', username: '[GITHUB_USERNAME]' }),
          new SocialProfile({ platform: 'Telegram', username: '[GITHUB_USERNAME]' }),
        ],
      }),
      new HeadingElement({ text: 'Stats', level: 2 }),
      new GitHubStatsElement({ repoName: '[GITHUB_USERNAME]/[PROJECT_NAME]' }),
    ],
  },
  {
    name: 'SaaS / Product',
    description: 'A product page-style README with sections and a demo embed.',
    elements: [
      new HeadingElement({ text: '[PROJECT_NAME]', level: 1 }),
      new ParagraphElement({ text: 'A premium workflow for creating stunning markdown documentation.' }),
      new BadgeElement({ label: 'Version', imageUrl: 'https://img.shields.io/badge/version-1.0.0-6366F1?style=for-the-badge', targetUrl: '' }),
      new BadgeElement({ label: 'Docs', imageUrl: 'https://img.shields.io/badge/docs-online-10B981?style=for-the-badge', targetUrl: 'https://example.com/docs' }),
      new DividerElement({}),
      new HeadingElement({ text: 'Demo', level: 2 }),
      new ParagraphElement({ text: 'Watch a quick walkthrough:' }),
      { type: 'youtube', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', provider: 'youtube', typeName: 'youtube' },
      new HeadingElement({ text: "Why you'll love it", level: 2 }),
      new ListElement({ items: ['Professional templates', 'Drag & drop builder', 'One-click export', 'GitHub workflows'] }),
      new HeadingElement({ text: 'FAQ', level: 2 }),
      new CollapsibleElement({ summary: 'Is it free?', content: 'Yes - Pro is currently free for everyone.' }),
      new CollapsibleElement({ summary: 'Can I publish to GitHub?', content: 'Yes - connect a token and publish directly.' }),
      new HeadingElement({ text: 'License', level: 2 }),
      new ParagraphElement({ text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]' }),
    ],
  },
];
